services:

  ci:
    build: .
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    command: >
      bash -c "bundle exec rails webpacker:install
      && bundle exec rails db:create db:migrate
      && bundle exec rails test"

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
