services:

  web:
    build: .
    volumes:
      - .:/task_manager
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
